Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "server1/server1.py", line 94, in new_message_handler
    await group_channels.update_channels_from_mongo(collection_channels_id)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 17 !/server1/class_group.py", line 41, in update_channels_from_mongo
    for channel in channels:
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 599, in _check_session_support
    self._select_servers_loop(
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131),SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131), Timeout: 30s, Topology Description: <TopologyDescription id: 6526c166bdb31568bf46d46a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-abi7tte-shard-00-00.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-00.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-01.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-01.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>, <ServerDescription ('ac-abi7tte-shard-00-02.pysxbay.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-abi7tte-shard-00-02.pysxbay.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1131)')>]>
openai model for propaganda marks = gpt-4
openai model for affirmations     = gpt-3.5-turbo
temperature                       = 0.2
max_len_telegram_message          = 600
verification of the messages for the last 0.016 hours

0  positive author attitude
1  the message is advantageous for the actual political power
2  exaggerations
3  lack of object concordance
4  appeal to the intellect
5  appeal to emotions
6  appeal to virtues
7  appeal to ethics
8  appeal to blinding generalities as fatherland, peace, glory, justice, honor
9  appeal to fear
10 appeal to the threat from other countries
11 appeal to hatred
12 appeal to authority
13 appeal to human rights
14 criticism of the actual political power
15 generalizations
16 seemingly scientific appearance, but only seemingly
17 real scientific proofs of the information
18 real proofs of the information
19 euphemismes replacing offensive expressions
20 euphemismes replacing war or victims
21 formal register of the texte
22 beneficiaries of the information regarding to politics
23 flattery to the reader
24 dilemma between only two possibilities
25 criticisme of a person instead of criticism of his arguments
26 underestimation of the proofs of the opponents

server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
server1 listens to the channels {-1001944316671, -1001842901217, -1001919265899, -1001863996867, -1001905441409}
