Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/Users/nicolas/TelegramBots/LastStage/src/main.py", line 97, in new_message_handler
    channels_names = get_channel_names_from_db()  # Fetch the channels list each time
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/TelegramBots/LastStage/src/main.py", line 93, in get_channel_names_from_db
    return [channel['id'] for channel in channels]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/TelegramBots/LastStage/src/main.py", line 93, in <listcomp>
    return [channel['id'] for channel in channels]
            ~~~~~~~^^^^^^
KeyError: 'id'
Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/Users/nicolas/TelegramBots/LastStage/src/main.py", line 97, in new_message_handler
    channels_names = get_channel_names_from_db()  # Fetch the channels list each time
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/TelegramBots/LastStage/src/main.py", line 93, in get_channel_names_from_db
    return [channel['id'] for channel in channels]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolas/TelegramBots/LastStage/src/main.py", line 93, in <listcomp>
    return [channel['id'] for channel in channels]
            ~~~~~~~^^^^^^
KeyError: 'id'
model           = gpt-4
temperature     = 0.2
max_len_message = 600

