model          = gpt-3.5-turbo
nb_messages    = 8
temperature    = 0.0
live_mode      = 0


*********************************************************

calculating dist  @khodorkovski                    @teamnavalny                     04/10/2023 20:43:30 ...
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    client_tg.loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 93, in main
    await group.calc_distances_via_openai(model, temperature, promptD)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 7/src/class_group.py", line 100, in calc_distances_via_openai
    response_openai = openai.ChatCompletion.create(
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
