Unhandled exception on new_message_handler
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/telethon/client/updates.py", line 520, in _dispatch_update
    await callback(event)
  File "main.py", line 92, in new_message_handler
    await group.new_message_handler(event, promptC, promptA, model, temperature, max_tokens, request_timeout, collection_messages)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 7/src/class_group.py", line 22, in new_message_handler
    await message.put_to_mongo(prompt_c, prompt_a, collection_messages)
  File "/mnt/md0/travail hobby/2022 2023 stage/github 7/src/class_message.py", line 54, in put_to_mongo
    collection_messages.deleteMany({}) ################## TMP
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/collection.py", line 3213, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'deleteMany' method on a 'Collection' object it is failing because no such method exists.
model           = gpt-3.5-turbo
temperature     = 0.0
max_len_message = 600
channels        = [-1001842901217, -1001905441409, -1001863996867, -1001944316671, -1001919265899]

0  positive author attitude
1  the message is advantageous for the actual political power
2  exaggerations
3  lack of object concordance
4  appeal to the intellect
5  appeal to emotions
6  appeal to virtues
7  appeal to ethics
8  appeal to blinding generalities as fatherland, peace, glory, justice, honor
9  appeal to fear
10 appeal to the threat from other countries
11 appeal to hatred
12 appeal to authority
13 appeal to human rights
14 criticism of the actual political power
15 generalizations
16 seemingly scientific appearance, but only seemingly
17 real scientific proofs of the information
18 real proofs of the information
19 euphemismes replacing offensive expressions
20 euphemismes replacing war or victims
21 formal register of the texte
22 eupbeneficiaries of the information regarding to politics
23 flattery to the reader
24 dilemma between only two possibilities
25 criticisme of a person instead of criticism of his arguments
26 underestimation of the proofs of the opponents

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/an/.local/lib/python3.8/site-packages/pymongo/periodic_executor.py", line 100, in join
    self._thread.join(timeout)
  File "/usr/lib/python3.8/threading.py", line 1015, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
