model      = gpt-4
nb_message = 10
temperature = 0.73

@nowar_ukraina                   28/09/2023 18h08 ...
Traceback (most recent call last):
  File "test.py", line 501, in <module>
    client_tg.loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 464, in main
    await channel.evaluate(NB_MESSAGES)
  File "test.py", line 167, in evaluate
    await message.evaluate(self.prompt)
  File "test.py", line 85, in evaluate
    response_to_msg = openai.ChatCompletion.create( # object OpenAIObject can't be used in 'await'  ???
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/home/an/.local/lib/python3.8/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-XF2UyMG0Qpw50VogHx2c4oFI on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.
